#!/bin/bash

INFILE=`echo $1 | awk -F . '{ print $1 }'`
echo ""
echo "input file: $1 -> $INFILE"
echo ""
echo "----------"
echo ""
echo 'Sweave("'$INFILE'", compile.tex=FALSE)' | R --vanilla --quiet
echo ""
echo "----------"
echo ""
echo "pdflatex"
echo ""
echo "----------"
echo ""
pdflatex "$INFILE"
echo ""
echo "----------"
echo ""
bibtex "$INFILE"
echo ""
echo "----------"
echo ""
pdflatex "$INFILE"
echo ""
echo "----------"
echo ""
pdflatex "$INFILE"
